apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: techtrends
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{.Values.image.user}}/{{.Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        name: techtrends
        resources:
{{toYaml .Values.resoures | indent 12}}        
        ports:
        - containerPort: {{.Values.containerPort}}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{.Values.livenessProbe.path}}
            port: {{.Values.livenessProbe.port }} 
        readinessProbe:
          httpGet:
            path: {{.Values.readinessProbe.path}}
            port: {{ .Values.readinessProbe.port }} 
