namespace: sandbox

service:
  port: 4111
  targerPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources: 
  requests:
    memory: "64Mi"
    CPU: "250m"
  limits:
    memory: "128Mi"
    CPU: "500m"

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz
